NAME := libft.a

.PHONY: all
all: $(NAME)

$(NAME):
	$(MAKE) -C .. libft

.PHONY: clean
clean:
	$(MAKE) -C .. libft_clean

.PHONY: fclean
fclean:
	$(MAKE) -C .. libft_fclean

.PHONY: re
re:
	$(MAKE) -C .. libft_re
